from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions, name='transactions'),
    path('download-transactions/', views.download_transactions, name='download_transactions'),
    path('add-income/', views.add_income, name='add_income'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('profile/', views.profile, name='profile'),
    path('update-email/', views.update_email, name='update_email'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('budget/', views.budget, name='budget'),
    path('budget/edit/<int:budget_id>/', views.edit_budget, name='edit_budget'),
    path('budget/delete/<int:budget_id>/', views.delete_budget, name='delete_budget'),
    path('savings-goals/', views.savings_goals, name='savings_goals'),
    path('savings-goals/edit/<int:goal_id>/', views.edit_savings_goal, name='edit_savings_goal'),
    path('savings-goals/delete/<int:goal_id>/', views.delete_savings_goal, name='delete_savings_goal'),
    path('check-debits/', views.check_debits, name='check_debits'),
    path('check-debits/force/', views.check_debits, {"force": True}, name='force_check_debits'),
    path('savings-analytics/', views.savings_analytics, name='savings_analytics'),
    path('finance-insights/', views.finance_insights, name='finance_insights'),
    path('recurring-transactions/', views.recurring_transactions, name='recurring_transactions'),
    path('recurring-transactions/add/', views.add_recurring_transaction, name='add_recurring_transaction'),
    path('recurring-transactions/<int:transaction_id>/', views.edit_recurring_transaction, name='get_recurring_transaction'),
    path('recurring-transactions/<int:transaction_id>/edit/', views.edit_recurring_transaction, name='edit_recurring_transaction'),
    path('recurring-transactions/<int:transaction_id>/delete/', views.delete_recurring_transaction, name='delete_recurring_transaction'),
    path('mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('check-transactions/', views.check_transactions, name='check_transactions'),
    path('confirm-transaction/<int:transaction_id>/', views.confirm_transaction, name='confirm_transaction'),
    path('community/', views.community_view, name='community'),
    path('manage-categories/', views.manage_categories, name='manage_categories'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
]