# Generated by Django 5.1.6 on 2025-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='auto_debit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='last_debit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
