# Generated by Django 5.1.6 on 2025-03-28 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_savingsgoal_auto_debit_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='debit_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Time for automatic debits'),
        ),
    ]
