# Generated by Django 5.1.6 on 2025-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_savingsgoal_debit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='debit_day',
            field=models.IntegerField(default=1, help_text='Day of month for automatic debits (1-28)'),
        ),
    ]
