# Generated by Django 5.1.6 on 2025-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_savingsgoal_debit_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='last_debit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
