# Generated by Django 5.1.6 on 2025-03-28 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_savingsgoal_last_debit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='debit_day',
            field=models.IntegerField(default=1, help_text='Day of month for automatic debits (1-31, will adjust for shorter months)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
