# Generated by Django 5.1.6 on 2025-03-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_recurringtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='end_date',
        ),
    ]
