# Generated by Django 5.1.6 on 2025-03-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
