# Generated by Django 5.1.6 on 2025-03-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='scheduled_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
