# Generated by Django 5.1.6 on 2025-03-29 03:18

from django.db import migrations

def update_notification_wording(apps, schema_editor):
    # Get the database connection
    db_alias = schema_editor.connection.alias
    TransactionNotification = apps.get_model('tracker', 'TransactionNotification')
    
    # Update notifications using raw SQL for string replacement
    TransactionNotification.objects.using(db_alias).filter(
        message__contains='has been incomed'
    ).update(
        message=migrations.RunSQL.noop('REPLACE(message, %s, %s)', ['has been incomed', 'has been credited'])
    )
    
    TransactionNotification.objects.using(db_alias).filter(
        message__contains='has been expensed'
    ).update(
        message=migrations.RunSQL.noop('REPLACE(message, %s, %s)', ['has been expensed', 'has been debited'])
    )

def reverse_notification_wording(apps, schema_editor):
    # Get the database connection
    db_alias = schema_editor.connection.alias
    TransactionNotification = apps.get_model('tracker', 'TransactionNotification')
    
    # Reverse the changes using raw SQL for string replacement
    TransactionNotification.objects.using(db_alias).filter(
        message__contains='has been credited'
    ).update(
        message=migrations.RunSQL.noop('REPLACE(message, %s, %s)', ['has been credited', 'has been incomed'])
    )
    
    TransactionNotification.objects.using(db_alias).filter(
        message__contains='has been debited'
    ).update(
        message=migrations.RunSQL.noop('REPLACE(message, %s, %s)', ['has been debited', 'has been expensed'])
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_discussion_comment'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL
            sql=[
                "UPDATE tracker_transactionnotification SET message = REPLACE(message, 'has been incomed', 'has been credited') WHERE message LIKE '%has been incomed%';",
                "UPDATE tracker_transactionnotification SET message = REPLACE(message, 'has been expensed', 'has been debited') WHERE message LIKE '%has been expensed%';"
            ],
            # Reverse SQL
            reverse_sql=[
                "UPDATE tracker_transactionnotification SET message = REPLACE(message, 'has been credited', 'has been incomed') WHERE message LIKE '%has been credited%';",
                "UPDATE tracker_transactionnotification SET message = REPLACE(message, 'has been debited', 'has been expensed') WHERE message LIKE '%has been debited%';"
            ]
        )
    ]
