# Generated by Django 5.1.6 on 2025-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_userprofile_email_verified_userprofile_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
