# Generated by Django 5.1.6 on 2025-04-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_transaction_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
    ]
